typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done
fpath+=(@zsh_completions@/share/zsh/site-functions)

autoload -U compinit && compinit

source @zsh_autosuggestions@/share/zsh-autosuggestions/zsh-autosuggestions.zsh
. @fzf@/share/fzf/completion.zsh
. @fzf@/share/fzf/key-bindings.zsh
eval "$(@zoxide@/bin/zoxide init zsh)"
eval "$(@direnv@/bin/direnv hook zsh)"

export HISTSIZE="10000"
export SAVEHIST="0"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
unsetopt HIST_EXPIRE_DUPS_FIRST
unsetopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export KEYTIMEOUT=1
export EDITOR="nvim"
export VISUAL="nvim"
export GIT_EDITOR="nvim"
export LS_COLORS="no=00:fi=00:di=01;34:ln=35;40:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:"
export LSCOLORS="ExfxcxdxCxegedabagacad"
export FIGNORE="*.o:~:Application Scripts:CVS:.git"
export TZ="America/Denver"
export LESS="--raw-control-chars -FXRadeqs -P--Less--?e?x(Next file: %x):(END).:?pB%pB%."
export CLICOLOR=1
export CLICOLOR_FORCE="yes"
export PAGER="less"
# Add colors to man pages
export MANPAGER="less -R --use-color -Dd+r -Du+b +Gg -M -s"
export SYSTEMD_COLORS="true"
export FZF_CTRL_R_OPTS="--sort --exact"
# Prompt is left: [returncode in bold] user@machine> (machine is underlined). right: path relative to home
export PROMPT="%B%(?..[%?] )%b%n@%U%m%u> "
export RPROMPT="%~"
export PS1="%B%(?..[%?] )%b%n@%U%m%u> "
export PS2="%_> "
export PS3="?# i"
export PS4="+%N:%i> "
export STARSHIP_CONFIG=@starshipconfig@

set -o vi
bindkey -v

# Setup preferred key bindings that emulate the parts of
# emacs-style input manipulation that I'm familiar with
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '\e^h' backward-kill-word
bindkey '\e^?' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '\eb' backward-word
bindkey '\ef' forward-word
bindkey '^k' kill-line
bindkey '^u' backward-kill-line

# I prefer for up/down and j/k to do partial searches if there is
# already text in play, rather than just normal through history
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey -M vicmd 'k' up-line-or-search
bindkey -M vicmd 'j' down-line-or-search
bindkey '^r' history-incremental-search-backward
bindkey '^s' history-incremental-search-forward

# You might not like what I'm doing here, but '/' works like ctrl-r
# and matches as you type. I've added pattern matches here though.

bindkey -M vicmd '/' history-incremental-pattern-search-backward # default is vi-history-search-backward
bindkey -M vicmd '?' vi-history-search-backward # default is vi-history-search-forward

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

setopt list_ambiguous


# Aliases
alias f='\fd -H'
alias fd='\fd -H -t d'
alias l='eza --icons --git-ignore --git -F --extended'
alias ll='eza --icons --git-ignore --git -F --extended -l'
alias llt='eza --icons --git-ignore --git -F --extended -l -T'
alias ls='ls --color=auto -F'
alias lt='eza --icons --git-ignore --git -F --extended -T'
alias n='zk edit --interactive'


zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' menu select
zstyle ':completion:*:manuals'    separate-sections true
zstyle ':completion:*:manuals.*'  insert-sections   true
zstyle ':completion:*:man:*'      menu yes select
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
zstyle ':completion:*:(all-|)files' ignored-patterns '(|*/)CVS'
zstyle ':completion:*:cd:*' ignored-patterns '(*/)#CVS'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*'   force-list always
# TODO: need to look this up as below is broken
zstyle -e ':completion:*:default' list-colors 'reply=("$${PREFIX:+=(#bi)($PREFIX:t)(?)*==34=34}:${(s.:.)LS_COLORS}")'

zmodload -a colors
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" # complete with same colors as ls
zstyle ':completion:*:*:*:*:hosts' list-colors '=*=1;36' # bold cyan
zstyle ':completion:*:*:*:*:users' list-colors '=*=36;40' # dark cyan on black



# source @zsh_autocomplete@/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source @zsh_syntax_highlighting@/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

zmodload -a autocomplete
zmodload -a complist

if ls -1 /Library/Fonts/ /usr/share/fonts/ ~/.local/share/fonts/ /usr/share/fonts/truetype/ ~/Library/Fonts/ |& grep -q "Nerd Font"; then
  # we can't know if they are available, but if true type fonts are installed, let's just go for it
  echo 'Found nerdfonts, using starship for prompt'
  echo ""
  eval "$(@starship@/bin/starship init zsh)"
else
  echo "If you have a nerd font, run: "
  echo "eval \"\$(starship init zsh)\""
  echo ""
fi
